//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Dev_Template_Generator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_Dev_Template_Generator.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function customDemo() {
        ///    alert(&quot;Thank You For Clicking Me&quot;)
        ///}.
        /// </summary>
        internal static string advanced_app {
            get {
                return ResourceManager.GetString("advanced_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] advanced_background {
            get {
                object obj = ResourceManager.GetObject("advanced_background", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] advanced_fav {
            get {
                object obj = ResourceManager.GetObject("advanced_fav", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] advanced_global {
            get {
                object obj = ResourceManager.GetObject("advanced_global", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] advanced_head {
            get {
                object obj = ResourceManager.GetObject("advanced_head", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] advanced_index {
            get {
                object obj = ResourceManager.GetObject("advanced_index", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap&quot;);
        ///* {
        ///  box-sizing: border-box;
        ///  margin: 0;
        ///  padding: 0;
        ///  -webkit-user-select: none;
        ///     -moz-user-select: none;
        ///      -ms-user-select: none;
        ///          user-select: none;
        ///  outline: none;
        ///  color: blanchedalmond;
        ///  font-family: &quot;Roboto&quot;, sans-serif;
        ///}
        ///
        ///.flex {
        ///  display: flex;
        ///}
        ///
        ///.justify-c-c {
        ///  justify-content: center;
        ///}
        ///
        ///.align-i-c {
        ///  align-item [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string advanced_main {
            get {
                return ResourceManager.GetString("advanced_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] advanced_main_scss {
            get {
                object obj = ResourceManager.GetObject("advanced_main_scss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] beginner_fav {
            get {
                object obj = ResourceManager.GetObject("beginner_fav", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;./assets/icons/fav.png&quot; type=&quot;image/x-icon&quot;&gt;
        ///    &lt;title&gt;Tab Title&lt;/title&gt;
        ///
        ///    &lt;style&gt;
        ///        * {
        ///            box-sizing: border-box;
        ///            margin: 0;
        ///            padding: 0;
        ///            color: azure;
        ///            font-family: sans-serif;
        ///        }
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string beginner_index {
            get {
                return ResourceManager.GetString("beginner_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.d8888. db    db  .o88b.  .o88b. d88888b .d8888. .d8888.
        ///88&apos;  YP 88    88 d8P  Y8 d8P  Y8 88&apos;     88&apos;  YP 88&apos;  YP
        ///`8bo.   88    88 8P      8P      88ooooo `8bo.   `8bo.
        ///  `Y8b. 88    88 8b      8b      88~~~~~   `Y8b.   `Y8b.
        ///db   8D 88b  d88 Y8b  d8 Y8b  d8 88.     db   8D db   8D
        ///`8888Y&apos; ~Y8888P&apos;  `Y88P&apos;  `Y88P&apos; Y88888P `8888Y&apos; `8888Y&apos;
        ///.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d88888b d8888b. d8888b.  .d88b.  d8888b.
        ///88&apos;     88  `8D 88  `8D .8P  Y8. 88  `8D
        ///88ooooo 88oobY&apos; 88oobY&apos; 88    88 88oobY&apos;
        ///88~~~~~ 88`8b   88`8b   88    88 88`8b
        ///88.     88 `88. 88 `88. `8b  d8&apos; 88 `88.
        ///Y88888P 88   YD 88   YD  `Y88P&apos;  88   YD
        ///.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] intermediate_background {
            get {
                object obj = ResourceManager.GetObject("intermediate_background", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] intermediate_fav {
            get {
                object obj = ResourceManager.GetObject("intermediate_fav", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] intermediate_global {
            get {
                object obj = ResourceManager.GetObject("intermediate_global", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;./css/main.css&quot;&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;./assets/icons/fav.png&quot; type=&quot;image/x-icon&quot;&gt;
        ///    &lt;title&gt;Tab Title&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body class=&quot;flex justify-c-c align-i-c&quot;&gt;
        ///    &lt;div class=&quot;container flex justify-c-c align-i-c flex-dir&quot;&gt;
        ///        &lt;h1&gt;Cascaded S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string intermediate_index {
            get {
                return ResourceManager.GetString("intermediate_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap&quot;);
        ///* {
        ///  box-sizing: border-box;
        ///  margin: 0;
        ///  padding: 0;
        ///  -webkit-user-select: none;
        ///     -moz-user-select: none;
        ///      -ms-user-select: none;
        ///          user-select: none;
        ///  outline: none;
        ///  color: blanchedalmond;
        ///  font-family: &quot;Roboto&quot;, sans-serif;
        ///}
        ///
        ///.flex {
        ///  display: flex;
        ///}
        ///
        ///.justify-c-c {
        ///  justify-content: center;
        ///}
        ///
        ///.align-i-c {
        ///  align-item [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string intermediate_main {
            get {
                return ResourceManager.GetString("intermediate_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] intermediate_main_scss {
            get {
                object obj = ResourceManager.GetObject("intermediate_main_scss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///db   d8b   db d88888b d8888b.
        ///88   I8I   88 88&apos;     88  `8D
        ///88   I8I   88 88ooooo 88oooY&apos;
        ///Y8   I8I   88 88~~~~~ 88~~~b.
        ///`8b d8&apos;8b d8&apos; 88.     88   8D
        /// `8b8&apos; `8d8&apos;  Y88888P Y8888P&apos;
        ///
        ///d8888b. d88888b db    db
        ///88  `8D 88&apos;     88    88
        ///88   88 88ooooo Y8    8P
        ///88   88 88~~~~~ `8b  d8&apos;
        ///88  .8D 88.      `8bd8&apos;
        ///Y8888D&apos; Y88888P    YP
        ///
        ///d888888b d88888b .88b  d88. d8888b. db       .d8b.  d888888b d88888b
        ///`~~88~~&apos; 88&apos;     88&apos;YbdP`88 88  `8D 88      d8&apos; `8b `~~88~~&apos; 88&apos;
        ///   88    88ooooo 88  88  88 88oo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
